version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SERVER_URL: "http://server:8000"